package pojos;
// Generated Nov 5, 2018 10:17:13 PM by Hibernate Tools 4.3.1



/**
 * Laporan generated by hbm2java
 */
public class Laporan  implements java.io.Serializable {


     private String idLaporan;
     private String status;

    public Laporan() {
    }

    public Laporan(String idLaporan, String status) {
       this.idLaporan = idLaporan;
       this.status = status;
    }
   
    public String getIdLaporan() {
        return this.idLaporan;
    }
    
    public void setIdLaporan(String idLaporan) {
        this.idLaporan = idLaporan;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


