package pojos;
// Generated Nov 22, 2018 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private String idPemesanan;
     private String noKtp;
     private String nama;
     private String alamat;
     private String namaBarang;
     private String jumlahBarang;
     private Date waktuAntar;
     private String status;

    public Pesanan() {
    }

    public Pesanan(String idPemesanan, String noKtp, String nama, String alamat, String namaBarang, String jumlahBarang, Date waktuAntar, String status) {
       this.idPemesanan = idPemesanan;
       this.noKtp = noKtp;
       this.nama = nama;
       this.alamat = alamat;
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.waktuAntar = waktuAntar;
       this.status = status;
    }
   
    public String getIdPemesanan() {
        return this.idPemesanan;
    }
    
    public void setIdPemesanan(String idPemesanan) {
        this.idPemesanan = idPemesanan;
    }
    public String getNoKtp() {
        return this.noKtp;
    }
    
    public void setNoKtp(String noKtp) {
        this.noKtp = noKtp;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(String jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public Date getWaktuAntar() {
        return this.waktuAntar;
    }
    
    public void setWaktuAntar(Date waktuAntar) {
        this.waktuAntar = waktuAntar;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


