package pojos;
// Generated Nov 5, 2018 10:17:13 PM by Hibernate Tools 4.3.1



/**
 * Proses generated by hbm2java
 */
public class Proses  implements java.io.Serializable {


     private String status;

    public Proses() {
    }

    public Proses(String status) {
       this.status = status;
    }
   
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


