package pojos;
// Generated Nov 22, 2018 12:36:04 AM by Hibernate Tools 4.3.1



/**
 * Stockbarang generated by hbm2java
 */
public class Stockbarang  implements java.io.Serializable {


     private String idBarang;
     private String namaBarang;
     private String jumlahStockBarang;

    public Stockbarang() {
    }

    public Stockbarang(String idBarang, String namaBarang, String jumlahStockBarang) {
       this.idBarang = idBarang;
       this.namaBarang = namaBarang;
       this.jumlahStockBarang = jumlahStockBarang;
    }
   
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getJumlahStockBarang() {
        return this.jumlahStockBarang;
    }
    
    public void setJumlahStockBarang(String jumlahStockBarang) {
        this.jumlahStockBarang = jumlahStockBarang;
    }




}


