package pojos;
// Generated Dec 17, 2018 3:26:41 PM by Hibernate Tools 4.3.1



/**
 * Stockbarang generated by hbm2java
 */
public class Stockbarang  implements java.io.Serializable {


     private String idBarang;
     private String namaBarang;
     private int harga;

    public Stockbarang() {
    }

    public Stockbarang(String idBarang, String namaBarang, int harga) {
       this.idBarang = idBarang;
       this.namaBarang = namaBarang;
       this.harga = harga;
    }
   
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }




}


