package pojos;
// Generated Nov 5, 2018 10:17:13 PM by Hibernate Tools 4.3.1



/**
 * Stockbarang generated by hbm2java
 */
public class Stockbarang  implements java.io.Serializable {


     private String jumlahStockBarang;

    public Stockbarang() {
    }

    public Stockbarang(String jumlahStockBarang) {
       this.jumlahStockBarang = jumlahStockBarang;
    }
   
    public String getJumlahStockBarang() {
        return this.jumlahStockBarang;
    }
    
    public void setJumlahStockBarang(String jumlahStockBarang) {
        this.jumlahStockBarang = jumlahStockBarang;
    }




}


